export const CATEGORIES = [
  "SOCIAL_ASSISTANCE",
  "ENVIRONMENTAL_ACTIVITIES",
  "EDUCATION_MENTORING",
  "MEDICAL_SERVICES",
  "SUPPORT_FOR_ELDERLY",
  "ANIMAL_WELFARE",
  "CULTURAL_INITIATIVES",
  "HUMANITARIAN_MISSIONS",
  "SPORTS_INITIATIVES",
  "CRISIS_RESPONSE_VOLUNTEERING",
];
